project:
  type: website

website:
  title: "BARRENADORES EN VERACRUZ"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/juanjo-maker/BARRENADORES-EN-VERACRUZ.git
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css

editor: visual

